Repository AnimealProject/animeal_android, pull requests merged in 2022-10, with the labels that each got.

#80 EPMEDU-785 [UI] Favourite feeding points page
  feature/home/src/main/java/com/epmedu/animeal/home/data/FeedingPointRepositoryImpl.kt
  feature/home/src/main/java/com/epmedu/animeal/home/data/model/FeedStatus.kt
  feature/home/src/main/java/com/epmedu/animeal/home/data/model/FeedingPoint.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/FeedingPointSheet.kt
  feature/tabsflow/favourites/.gitignore
  feature/tabsflow/favourites/build.gradle.kts
  feature/tabsflow/favourites/consumer-rules.pro
  feature/tabsflow/favourites/src/main/AndroidManifest.xml
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/FavouritesScreen.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/FavouritesScreenEvent.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/FavouritesScreenUI.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/FavouritesState.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/FavouritesViewModel.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/data/FavouritesRepository.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/data/FavouritesRepositoryImpl.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/data/model/FavouriteFeedingPoint.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/di/FavouritesModule.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/ui/FavouriteFeedingPointItem.kt
  feature/tabsflow/tabs/build.gradle.kts
  feature/tabsflow/tabs/src/main/java/com/epmedu/animeal/tabs/NavigationTab.kt
  feature/tabsflow/tabs/src/main/java/com/epmedu/animeal/tabs/Screens.kt
  feature/tabsflow/tabs/src/main/java/com/epmedu/animeal/tabs/TabsHost.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealHeartButton.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/FeedStatus.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/theme/Color.kt
  library/resources/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: Ready for review, Ready to merge

#58 EPMEDU-823: Add markers to map
  feature/home/src/main/java/com/epmedu/animeal/home/data/FeedingPointRepository.kt
  feature/home/src/main/java/com/epmedu/animeal/home/data/FeedingPointRepositoryImpl.kt
  feature/home/src/main/java/com/epmedu/animeal/home/data/model/FeedingPoint.kt
  feature/home/src/main/java/com/epmedu/animeal/home/data/model/enum/AnimalPriority.kt
  feature/home/src/main/java/com/epmedu/animeal/home/data/model/enum/AnimalState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/data/model/enum/Remoteness.kt
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenEvent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/model/FeedStatus.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/model/FeedingPointUi.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/model/GpsSettingState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/FeedingPointSheet.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/GeoLocationFloatingActionButton.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/MapboxMap.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/map/MapBoxInitOptions.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/map/MapUiSettings.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/map/MapView.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/map/MarkerController.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/utils/MarkerCache.kt
  gradle/libs.versions.toml
  library/extensions/build.gradle.kts
  library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
  library/extensions/src/main/java/com/epmedu/animeal/extensions/Operation.kt
  library/extensions/src/main/java/com/epmedu/animeal/extensions/StableList.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/switch/AnimealSwitch.kt
  library/resources/src/main/res/drawable/ic_catsstate_cathungry_high.xml
  library/resources/src/main/res/drawable/ic_catsstate_cathungry_low.xml
  library/resources/src/main/res/drawable/ic_catsstate_cathungry_medium.xml
  library/resources/src/main/res/drawable/ic_dogsstate_doghungry_high.xml
  library/resources/src/main/res/drawable/ic_dogsstate_doghungry_low.xml
  library/resources/src/main/res/drawable/ic_dogsstate_doghungry_medium.xml
  library/resources/src/main/res/drawable/ic_favstate_favouritehungry_high.xml
  library/resources/src/main/res/drawable/ic_favstate_favouritehungry_low.xml
  library/resources/src/main/res/drawable/ic_favstate_favouritehungry_medium.xml
Labels: Ready for review

#88 [EPMEDU-915]: Digits and symbols are allowed for Name and Surname fields
  library/extensions/src/main/java/com/epmedu/animeal/extensions/String.kt
  library/foundation/build.gradle.kts
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/result/NameValidationResult.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/result/SurnameValidationResult.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/validator/NameValidator.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/validator/SurnameValidator.kt
  library/resources/src/main/res/values/strings.xml
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/ValidateNameUseCase.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/ValidateSurnameUseCase.kt
Labels: Ready to merge

#90 Add Firebase Analytics library into dependencies
  gradle/libs.versions.toml
  library/analytics/.gitignore
  library/analytics/build.gradle.kts
  library/analytics/consumer-rules.pro
  library/analytics/src/main/AndroidManifest.xml
  library/analytics/src/main/java/com/epmedu/animeal/analytics/AnalyticsManager.kt
  library/analytics/src/main/java/com/epmedu/animeal/analytics/AnalyticsManagerImpl.kt
  library/analytics/src/main/java/com/epmedu/animeal/analytics/AnalyticsParameterKey.kt
  library/analytics/src/main/java/com/epmedu/animeal/analytics/di/AnalyticsModule.kt
  settings.gradle.kts
Labels: Ready to merge

#91 [EPMEDU-918]: Add age validation
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/Constants.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/result/BirthDateValidationResult.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/validator/BirthDateValidator.kt
  library/resources/src/main/res/values/strings.xml
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/ValidateBirthDateUseCase.kt
Labels: Ready for review

#92 Remove suspend for Flow
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/data/FavouritesRepository.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/data/FavouritesRepositoryImpl.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/repository/ProfileRepository.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/repository/ProfileRepositoryImpl.kt
Labels: Ready for review

#94 [EPMEDU-863]: Crash application if amplify config not found
  app/src/main/java/com/epmedu/animeal/AnimealApplication.kt
Labels: Ready for review

#93 Fix glitch effect between switching tabs
  feature/tabsflow/analytics/src/main/java/com/epmedu/animeal/tabs/analytics/AnalyticsScreenUi.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/SearchScreenUi.kt
Labels: Ready for review

#98 [EPMEDU-877]: Add back handler for bottom sheet component
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
Labels: Ready for review
