Repository AnimealProject/animeal_android, pull requests merged in 2023-05, with the labels that each got.

#185 EPMEDU-795 - Mark feeding done
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenEvent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/model/FeedingConfirmationState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/thankyou/ThankYouDialog.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/thankyou/ThankYouScreen.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/thankyou/ThankYouScreenUi.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/thankyou/ui/ThankYouContent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/HomeMapbox.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/DefaultFeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feedingpoint/DefaultFeedingPointHandler.kt
Labels: Ready for review

#189 [EPMEDU-1928]: Black screen instead of map
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomePresentationModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/providers/HomeProviders.kt
Labels: Ready for review

#190 EPMEDU-1894: Crash related to regions on old devices
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/model/Region.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ui/RegionsLazyColumn.kt
Labels: Ready for review

#192 [refactor/EPMEDU-1079]: Improve data store interactions
  app/src/main/java/com/epmedu/animeal/component/AppSettingsProviderImpl.kt
  app/src/main/java/com/epmedu/animeal/component/DataStorePreferences.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/data/EnterCodeRepositoryImpl.kt
  feature/signupflow/enterphone/src/main/java/com/epmedu/animeal/signup/enterphone/data/EnterPhoneRepositoryImpl.kt
  library/common/src/main/java/com/epmedu/animeal/common/constants/DataStorePreferencesKey.kt
  library/extensions/build.gradle.kts
  library/extensions/src/main/java/com/epmedu/animeal/extensions/Datastore.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/repository/ProfileRepositoryImpl.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/util/BirthDateDataStorePreferences.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/util/EmailDataStorePreferences.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/util/NameDataStorePreferences.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/util/PhoneNumberDataStorePreferences.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/util/SurnameDataStorePreferences.kt
Labels: Ready for review

#191 [EPMEDU-1951]: Wrong bottom sheet behaviour after tapping favourite button
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/DefaultFeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/FeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feedingpoint/DefaultFeedingPointHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feedingpoint/FeedingPointHandler.kt
  library/api/src/main/java/com/epmedu/animeal/api/storage/StorageApiImpl.kt
Labels: Ready for review

#195 Remove WillFeedEvent, WillFeedHandler and WillFeedState since there is no business logic behind them
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomePresentationModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/DefaultHomeHandler.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/FavouritesScreen.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/ui/FavouritesScreenUI.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesState.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesViewModel.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/SearchScreen.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/ui/SearchScreenUi.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchState.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchViewModel.kt
  shared/feature/feeding/build.gradle.kts
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/di/FeedPresentationModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/event/WillFeedEvent.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/ui/FeedingConfirmationDialog.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/WillFeedState.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/handler/willfeed/DefaultWillFeedHandler.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/handler/willfeed/WillFeedHandler.kt
Labels: Ready to merge

#193 EPMEDU-1791 - Request camera permissions before starting the feeding flow
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeDataModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/thankyou/ThankYouContent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/thankyou/ThankYouDialog.kt
  feature/tabsflow/favourites/build.gradle.kts
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/FavouritesScreen.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/ui/FavouritesScreenUI.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesState.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesViewModel.kt
  feature/tabsflow/search/build.gradle.kts
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/SearchScreen.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/ui/SearchScreenUi.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchState.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchViewModel.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealButton.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/dialog/AnimealQuestionDialog.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/text/AutoSizeText.kt
  library/resources/src/main/res/values/strings.xml
  shared/feature/permissions/build.gradle.kts
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/di/PermissionsModule.kt
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/presentation/ui/CameraPermissionRequestDialog.kt
Labels: Ready for review

#194 [EPMEDU-1793]: Ask user to give permission to use gps before starting the feeding flow
  app/src/main/java/com/epmedu/animeal/component/AppSettingsProviderImpl.kt
  app/src/main/java/com/epmedu/animeal/component/DataStorePreferences.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  library/common/src/main/java/com/epmedu/animeal/common/component/AppSettingsProvider.kt
  library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealButton.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealSecondaryButtonOutlined.kt
  library/resources/src/main/res/values/strings.xml
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/di/PermissionsModule.kt
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/domain/GetIsGeolocationPermissionRequestedAgainUseCase.kt
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/domain/UpdateIsGeolocationPermissionRequestedAgainUseCase.kt
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/presentation/PermissionsState.kt
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/presentation/handler/PermissionsHandlerImpl.kt
  shared/feature/permissions/src/main/java/com/epmedu/animeal/permissions/presentation/ui/GeolocationPermissionRequestDialog.kt
Labels: Ready to merge

#199 Fix empty images issue after receiving response from onUpdateFeedingPoint subscription
  library/api/src/main/java/com/epmedu/animeal/api/storage/StorageApiImpl.kt
Labels: Ready to merge

#162 EPMEDU-1054 Find a feeding point with the search bar
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/di/SearchModule.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/domain/SearchDogsFeedingPointsUseCase.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/domain/SearchFeedingPointsUseCase.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/ui/SearchFeedingPointsUi.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchViewModel.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/listitem/ExpandableListItem.kt
Labels: In Progress

#203 Fix squeezed feeding confirmation dialog button on small screens
  library/foundation/src/main/java/com/epmedu/animeal/foundation/preview/AnimealPreview.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/ui/FeedingConfirmationDialog.kt
Labels: Ready for review

#202 [EPMEDU-1982]: Incorrect colour and state of feeding point icon on the map after auto-cancellation of the feeding booking
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeDomainModule.kt
  library/api/src/main/java/com/epmedu/animeal/api/extensions/Api.kt
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FavouriteRepositoryMock.kt
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryMock.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FavouriteRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/di/FeedingDomainModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/di/FeedingPresentationModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FavouriteRepository.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingPointRepository.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/usecase/GetFeedingPointByIdUseCase.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/handler/feedingpoint/DefaultFeedingPointHandler.kt
Labels: Ready for review

#200 [EPMEDU-2016]: Show the user who has booked the feeding
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingApiImpl.kt
  library/codegen/consumer-rules.pro
  library/codegen/src/main/graphql/queries.graphql
  library/resources/src/main/res/values/strings.xml
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryMock.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/di/FeedDomainModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/di/FeedingDomainModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/di/FeedingPresentationModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/model/FeedingInProgress.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingRepository.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/usecase/GetFeedingInProgressUseCase.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/model/Feeding.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/model/FeedingHistory.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/model/FeedingPointModel.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/ui/FeedingPointSheet.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/handler/feedingpoint/DefaultFeedingPointHandler.kt
  shared/feature/users/src/main/java/com/epmedu/animeal/users/data/repository/UsersRepositoryImpl.kt
  shared/feature/users/src/main/java/com/epmedu/animeal/users/domain/UsersRepository.kt
Labels: Ready to merge

#206 [EPMEDU-1962]: Timer for current feeding is not correct
  library/common/src/main/java/com/epmedu/animeal/common/timer/TickerFlow.kt
  shared/feature/timer/src/main/java/com/epmedu/animeal/timer/data/repository/TimerRepositoryImpl.kt
Labels: Ready for review

#201 [EPMEDU-968]: Open the feeding point details from the favorites page
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/FavouritesScreenEvent.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/ui/FavouritesScreenUI.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesState.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesViewModel.kt
  shared/feature/feeding/build.gradle.kts
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/ui/FeedingPointSheet.kt
Labels: Ready for review

#205 [refactor/EPMEDU-1996]: Refactor UI events to simple UI logic
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/DonateScreen.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/DonateScreenEvent.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/DonateScreenUI.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/ui/DonateListItem.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/viewmodel/DonateState.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/viewmodel/DonateViewModel.kt
Labels: In Progress

#207 [EPMEDU-2077]: Refactor Api extension functions to a class
  library/api/src/main/java/com/epmedu/animeal/api/AnimealApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/AnimealApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/di/ApiModule.kt
  library/api/src/main/java/com/epmedu/animeal/api/donate/DonateApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/extensions/Api.kt
  library/api/src/main/java/com/epmedu/animeal/api/faq/FAQApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/favourite/FavouriteApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingPointApiImpl.kt
  shared/feature/users/src/main/java/com/epmedu/animeal/users/data/api/UsersApiImpl.kt
  shared/feature/users/src/main/java/com/epmedu/animeal/users/di/UsersModule.kt
Labels: Ready for review

#204 [EPMEDU-1055]: Open feeding point full details from the search page
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/domain/model/GroupFeedingPointsModel.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/SearchScreenEvent.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/ui/SearchFeedingPointsUi.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/ui/SearchScreenUi.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchState.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchViewModel.kt
Labels: Ready for review
