Repository AnimealProject/animeal_android, pull requests merged in 2023-04, with the labels that each got.

#157 EPMEDU-1579 - Wrong feeding point icon colour and (point) state on the map on the home page after auto cancellation of the feeding booking
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeDomainModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomePresentationModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/RejectFeedingUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenEvent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/FeedingExpiredDialog.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/DefaultFeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/FeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/timer/DefaultTimerHandler.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingPointApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingPointApiImpl.kt
  library/resources/src/main/res/values/strings.xml
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryMock.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingPointRepository.kt
Labels: Ready for review

#166 Fix sign in after session expiring
  library/auth/src/main/java/com/epmedu/animeal/auth/AuthAPI.kt
Labels: Ready for review

#165 [EPMEDU-1269]: Clean Architecture Adjustments
  feature/home/src/main/java/com/epmedu/animeal/home/data/ApplicationSettingsRepositoryImpl.kt
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeDataModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeDomainModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/ApplicationSettingsRepository.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/GetGeolocationPermissionRequestedSettingUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/UpdateGeolocationPermissionRequestedSettingUseCase.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/data/EnterCodeRepositoryImpl.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/di/EnterCodeModule.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/domain/EnterCodeRepository.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/domain/FacebookConfirmCodeUseCase.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/domain/GetPhoneNumberUseCase.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/domain/MobileConfirmCodeUseCase.kt
  feature/signupflow/entercode/src/main/java/com/epmedu/animeal/signup/entercode/domain/SendCodeUseCase.kt
  feature/signupflow/enterphone/src/main/java/com/epmedu/animeal/signup/enterphone/data/EnterPhoneRepositoryImpl.kt
  feature/signupflow/enterphone/src/main/java/com/epmedu/animeal/signup/enterphone/di/EnterPhoneModule.kt
  feature/signupflow/enterphone/src/main/java/com/epmedu/animeal/signup/enterphone/domain/EnterPhoneRepository.kt
  feature/signupflow/enterphone/src/main/java/com/epmedu/animeal/signup/enterphone/domain/SavePhoneNumberInfoUseCase.kt
  feature/signupflow/enterphone/src/main/java/com/epmedu/animeal/signup/enterphone/domain/SignUpAndSignInUseCase.kt
  feature/splash/src/main/java/com/epmedu/animeal/splash/di/SplashModule.kt
  feature/splash/src/main/java/com/epmedu/animeal/splash/domain/usecase/GetIsProfileSavedUseCase.kt
  library/auth/src/main/java/com/epmedu/animeal/auth/AuthAPI.kt
  library/auth/src/main/java/com/epmedu/animeal/auth/AuthAPIImpl.kt
  library/auth/src/main/java/com/epmedu/animeal/auth/di/AuthModule.kt
  shared/feature/networkuser/src/main/java/com/epmedu/animeal/networkuser/data/repository/AuthenticationTypeRepositoryImpl.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/repository/ProfileRepositoryImpl.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/di/ProfileModule.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/ClearProfileUseCase.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/GetProfileUseCase.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/LogOutUseCase.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/SaveProfileUseCase.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/repository/ProfileRepository.kt
Labels: Ready to merge

#169 EPMEDU-734 Get the permission to use camera
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epmedu/animeal/component/AppSettingsProviderImpl.kt
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeDomainModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/GetCameraPermissionRequestedUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/UpdateCameraPermissionRequestUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenEvent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/HomeGeolocationPermission.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/HomePermissions.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  library/common/src/main/java/com/epmedu/animeal/common/component/AppSettingsProvider.kt
  library/common/src/main/java/com/epmedu/animeal/common/constants/DataStorePreferencesKey.kt
Labels: Ready for review

#163 [Fix/EPMEDU-1481] Add app version to the page "About" footer
  feature/tabsflow/moreflow/about/build.gradle.kts
  feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreen.kt
  feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/AboutScreenUI.kt
  feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/state/AboutScreenState.kt
  feature/tabsflow/moreflow/about/src/main/java/com/epmedu/animeal/tabs/more/about/viewmodel/AboutScreenViewModel.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/theme/Color.kt
  library/resources/src/main/res/values/strings.xml
Labels: Ready for review

#150 [EPMEDU-1285]: Check if feeding is still in progress after app restart
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomeDomainModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomePresentationModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/CancelFeedingUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/FetchCurrentFeedingPointUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/FinishFeedingUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/RejectFeedingUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/domain/usecases/StartFeedingUseCase.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/DefaultFeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/FeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feedingpoint/DefaultFeedingPointHandler.kt
  library/api/src/main/java/com/epmedu/animeal/api/di/ApiModule.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingPointApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingPointApiImpl.kt
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryMock.kt
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryMock.kt
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/di/FeedingModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/DataToDomainFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/model/Feeding.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingPointRepository.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingRepository.kt
  shared/feature/feeding/src/release/java/com/epmedu/animeal/feeding/di/FeedingModule.kt
Labels: Ready for review

#168 [FIX/EPMEDU-1622] Show feeding point image in details view
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/ui/FavouritesScreenUI.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/ui/SearchFeedingPointsUi.kt
  library/api/src/main/java/com/epmedu/animeal/api/storage/StorageApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/storage/StorageApiImpl.kt
  library/resources/src/main/res/values/strings.xml
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryMock.kt
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/di/FeedingModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/DataToDomainFeedingPointMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/OnCreateFeedingPointToDomainMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/OnUpdateFeedingPointToDomainMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingPointRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/model/FeedingPoint.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/model/FeedingPointModel.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/ui/FeedingPointItem.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/ui/FeedingPointSheet.kt
  shared/feature/feeding/src/release/java/com/epmedu/animeal/feeding/di/FeedingModule.kt
Labels: In Progress

#179 [EPMEDU-1284]: Implement receiving payment credentials from server
  feature/tabsflow/moreflow/donate/build.gradle.kts
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/data/DonateRepositoryImpl.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/data/mapper/BankAccountToDonateInformation.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/di/DonateModule.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/domain/DonateInformation.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/DonateScreenEvent.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/DonateScreenUI.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/ui/DonateHeading.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/ui/DonateListItem.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/presentation/viewmodel/DonateViewModel.kt
  feature/tabsflow/moreflow/donate/src/main/java/com/epmedu/animeal/tabs/more/donate/util/DonateInformationStubList.kt
  library/api/src/main/java/com/epmedu/animeal/api/di/ApiModule.kt
  library/api/src/main/java/com/epmedu/animeal/api/donate/DonateApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/donate/DonateApiImpl.kt
  library/resources/src/main/res/drawable/ic_bank_of_georgia.xml
  library/resources/src/main/res/drawable/ic_paypal.xml
  library/resources/src/main/res/drawable/ic_tbc_bank.xml
Labels: Ready for review

#164 EPMEDU-731 - Updating requesting GPS permission and GPS location
  app/src/main/AndroidManifest.xml
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenEvent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/HomeMapbox.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/ui/map/MarkerController.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feeding/DefaultFeedingHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feedingpoint/DefaultFeedingPointHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/feedingpoint/FeedingPointHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/location/DefaultLocationHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/location/LocationHandler.kt
  library/extensions/build.gradle.kts
  library/extensions/src/main/java/com/epmedu/animeal/extensions/Context.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/theme/Color.kt
Labels: Ready for review

#183 [EPMEDU-1945] Move logic related to feeding corresponding share feature.
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/epmedu/animeal/home/di/HomePresentationModule.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreen.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenEvent.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/HomeScreenUI.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeState.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/HomeViewModel.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/DefaultHomeHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/willfeed/DefaultWillFeedHandler.kt
  feature/home/src/main/java/com/epmedu/animeal/home/presentation/viewmodel/handlers/willfeed/WillFeedHandler.kt
  feature/tabsflow/favourites/build.gradle.kts
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/FavouritesScreen.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/FavouritesScreenEvent.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/ui/FavouritesScreenUI.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesState.kt
  feature/tabsflow/favourites/src/main/java/com/epmedu/animeal/favourites/presentation/viewmodel/FavouritesViewModel.kt
  feature/tabsflow/search/build.gradle.kts
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/SearchScreen.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/SearchScreenEvent.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/ui/SearchScreenUi.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchState.kt
  feature/tabsflow/search/src/main/java/com/epmedu/animeal/tabs/search/presentation/viewmodel/SearchViewModel.kt
  feature/tabsflow/tabs/build.gradle.kts
  settings.gradle.kts
  shared/feature/feedconfirmation/.gitignore
  shared/feature/feedconfirmation/build.gradle.kts
  shared/feature/feedconfirmation/consumer-rules.pro
  shared/feature/feedconfirmation/src/main/java/AndroidManifest.xml
  shared/feature/feedconfirmation/src/main/java/com/epmedu/animeal/feedconfirmation/presentation/FeedConfirmationDialog.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/di/FeedPresentationModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/event/WillFeedEvent.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/ui/FeedConfirmationDialog.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/WillFeedState.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/handler/DefaultWillFeedHandler.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/presentation/viewmodel/handler/WillFeedHandler.kt
Labels: Ready for review
