Repository AnimealProject/animeal_android, pull requests merged in 2024-05, with the labels that each got.

#298 [EPMEDU-3560]: Implement disabled state for outlined buttons
  library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealButton.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealSecondaryButton.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/button/AnimealSecondaryButtonOutlined.kt
Labels: Ready for review

#297 [EPMEDU-3528]: Fix onboarding buttons alignment
  feature/signupflow/onboarding/src/main/java/com/epmedu/animeal/signup/onboarding/presentation/OnboardingScreenUI.kt
  feature/signupflow/onboarding/src/main/java/com/epmedu/animeal/signup/onboarding/presentation/ui/ButtonsBlock.kt
  feature/signupflow/onboarding/src/main/java/com/epmedu/animeal/signup/onboarding/presentation/ui/OnBoarding.kt
Labels: Ready for review

#301 Update schema and graphql operations
  library/codegen/src/main/graphql/mutations.graphql
  library/codegen/src/main/graphql/queries.graphql
  library/codegen/src/main/graphql/schema.json
  library/codegen/src/main/graphql/subscriptions.graphql
Labels: Ready to merge

#302 Add feeding subscriptions
  library/api/src/main/java/com/epmedu/animeal/api/AnimealApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/AnimealApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/di/ApiModule.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingActionApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingActionApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingApiImpl.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingFilters.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingHistoryApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingHistoryApiImpl.kt
  library/codegen/consumer-rules.pro
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/di/FeedDataModule.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/DataToDomainFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/DataToDomainFeedingStatusMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/FeedingHistoryToFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/release/java/com/epmedu/animeal/feeding/di/FeedDataModule.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreenUi.kt
Labels: Ready to merge

#304 Fix feeding confirmation image in dark mode
  library/resources/src/main/res/drawable/ic_will_feed_dialog.xml
Labels: Ready to merge

#299 [EPMEDU-1505]: View feeding card page (not reviewed)
  library/resources/src/main/res/values/strings.xml
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/DataToDomainFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/FeedingHistoryToFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/SearchFeedingToFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/model/Feeding.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreen.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreenEvent.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreenUi.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/model/FeedingModel.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/model/FeedingModelStatus.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingItem.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingItemButtons.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingItemSheetContent.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingItemSheetHeading.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingPhotoCarousel.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/viewmodel/FeedingsState.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/viewmodel/FeedingsViewModel.kt
Labels: Ready for review

#291 [EPMEDU-3526]: Adds empty screen for FeedingsScreenUI
  feature/tabsflow/analytics/src/main/java/com/epmedu/animeal/tabs/analytics/AnalyticsScreenUi.kt
  feature/tabsflow/home/src/main/java/com/epmedu/animeal/home/presentation/ui/thankyou/ThankYouContent.kt
  feature/tabsflow/moreflow/faq/src/main/java/com/epmedu/animeal/tabs/more/faq/presentation/ui/FAQEmptyState.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/AnimealPopUpScreen.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/placeholder/ComingSoonStub.kt
  library/resources/src/main/res/drawable/empty_screen_bone.xml
  library/resources/src/main/res/drawable/ic_analysis.xml
  library/resources/src/main/res/drawable/ic_analysis_soon.xml
  library/resources/src/main/res/drawable/ic_faqs_soon.xml
  library/resources/src/main/res/drawable/ic_magnifying_glass.xml
  library/resources/src/main/res/drawable/ic_questions.xml
  library/resources/src/main/res/values/strings.xml
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryMock.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/FeedingHistoryToFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/OnCreateFavouriteToFavouriteMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/model/Feeding.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingRepository.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/di/FeedingsDomainModule.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/domain/usecase/GetAllFeedingsUseCase.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/domain/usecase/GetHasReviewedFeedingsUseCase.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreenUi.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/viewmodel/FeedingsState.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/viewmodel/FeedingsViewModel.kt
  shared/feature/networkuser/src/main/java/com/epmedu/animeal/networkuser/data/repository/NetworkRepositoryImpl.kt
  shared/feature/networkuser/src/main/java/com/epmedu/animeal/networkuser/domain/repository/NetworkRepository.kt
Labels: In Progress

#305 [EPMEDU-1510]: Approve feeding from the feeding card
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingActionApi.kt
  library/api/src/main/java/com/epmedu/animeal/api/feeding/FeedingActionApiImpl.kt
  shared/feature/feeding/src/debug/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryMock.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/FeedingApiResultToActionResultMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/repository/FeedingRepository.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/di/FeedingsDomainModule.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/domain/usecase/ApproveFeedingUseCase.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreen.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreenEvent.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreenUi.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingItemSheetContent.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingPhotoCarousel.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/viewmodel/FeedingsState.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/viewmodel/FeedingsViewModel.kt
Labels: Ready for review

#307 [EPMEDU-3770]: Checkbox for user age instead of a birthdate
  feature/signupflow/finishprofile/src/main/java/com/epmedu/animeal/signup/finishprofile/presentation/ui/FinishProfileContent.kt
  feature/signupflow/finishprofile/src/main/java/com/epmedu/animeal/signup/finishprofile/presentation/viewmodel/FinishProfileViewModel.kt
  feature/tabsflow/moreflow/profile/src/main/java/com/epmedu/animeal/tabs/more/profile/viewmodel/ProfileViewModel.kt
  gradle/libs.versions.toml
  library/auth/src/main/java/com/epmedu/animeal/auth/constants/UserAttributesKey.kt
  library/extensions/src/main/java/com/epmedu/animeal/extensions/Date.kt
  library/foundation/build.gradle.kts
  library/foundation/src/main/java/com/epmedu/animeal/foundation/checkbox/AnimealSquareCheckbox.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/result/BirthDateValidationResult.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/validator/BirthDateValidator.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/validator/DefaultProfileValidator.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/common/validation/validator/ProfileValidator.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/dialog/DatePickerDialog.kt
  library/foundation/src/main/java/com/epmedu/animeal/foundation/theme/Color.kt
  library/resources/src/main/res/drawable-anydpi/ic_birthdate.xml
  library/resources/src/main/res/values/strings.xml
  shared/feature/networkuser/build.gradle.kts
  shared/feature/networkuser/src/main/java/com/epmedu/animeal/networkuser/data/mapper/AuthUserAttributesToProfileMapper.kt
  shared/feature/networkuser/src/main/java/com/epmedu/animeal/networkuser/data/mapper/ProfileToAuthUserAttributesMapper.kt
  shared/feature/networkuser/src/main/java/com/epmedu/animeal/networkuser/data/repository/NetworkRepositoryImpl.kt
  shared/feature/permissions/build.gradle.kts
  shared/feature/profile/build.gradle.kts
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/model/Profile.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/repository/ProfileRepositoryImpl.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/data/util/BirthDateDataStorePreferences.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/di/ProfileModule.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/domain/ValidateBirthDateUseCase.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ProfileInputFormEvent.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ui/AgeConfirmationCheckbox.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ui/BirthDateInput.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ui/BirthDateInputContent.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/ui/ProfileInputForm.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/viewmodel/ProfileInputFormState.kt
  shared/feature/profile/src/main/java/com/epmedu/animeal/profile/presentation/viewmodel/handler/ProfileInputFormHandlerImpl.kt
  shared/feature/timer/build.gradle.kts
Labels: Ready for review

#306 [EPMEDU-1819]: View feeding card page (reviewed/outdated feeding)
  library/resources/src/main/res/values/strings.xml
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/mapper/FeedingHistoryToFeedingMapper.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/data/repository/FeedingRepositoryImpl.kt
  shared/feature/feeding/src/main/java/com/epmedu/animeal/feeding/domain/model/Feeding.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/FeedingsScreenUi.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/model/FeedingModel.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingItemReviewDetails.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingItemSheetContent.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/ui/FeedingPhoto.kt
  shared/feature/feedings/src/main/java/com/epmedu/animeal/feedings/presentation/viewmodel/FeedingsViewModel.kt
Labels: Ready for review

#310 [EPMEDU-3284]: Non intuitive behavior of app
  feature/tabsflow/home/src/main/java/com/epmedu/animeal/home/utils/MapConstants.kt
Labels: Ready for review
